<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-08-03T16:23:57 EDT" name="Default suite" finished-at="2021-08-03T16:24:06 EDT" duration-ms="9388">
    <groups>
    </groups>
    <test started-at="2021-08-03T16:23:57 EDT" name="Default test" finished-at="2021-08-03T16:24:06 EDT" duration-ms="9388">
      <class name="Tests.Login_BillPay_Test">
        <test-method is-config="true" signature="setup()[pri:0, instance:Tests.Login_BillPay_Test@67080771]" started-at="2021-08-03T16:23:57 EDT" name="setup" finished-at="2021-08-03T16:24:02 EDT" duration-ms="5332" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testlogin()[pri:0, instance:Tests.Login_BillPay_Test@67080771]" started-at="2021-08-03T16:24:02 EDT" name="testlogin" finished-at="2021-08-03T16:24:06 EDT" duration-ms="3949" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Alert test incorrect expected [https://parabank.parasoft.com/parabank/about.tm] but found [https://parabank.parasoft.com/parabank/about.htm]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Alert test incorrect expected [https://parabank.parasoft.com/parabank/about.tm] but found [https://parabank.parasoft.com/parabank/about.htm]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at Tests.Login_BillPay_Test.testlogin(Login_BillPay_Test.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testlogin -->
      </class> <!-- Tests.Login_BillPay_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
